spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false #here gateway server is told to connect to eureka server and read individual microservice details
          #since we have configured custom paths like /eazybank/accounts, to kind of make it simple and not allow the regular
          #routing, this flag has been disabled
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info: #to show the environment related info in eureka dashboard we need to enable this actuator endpoint
    env:
      enabled: true

info: #to show these info in Eureka dashboard and its exposed via actuator endpoint
  app:
    name: "gatewayserver"
    description: "Soft Bank Gateway server"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"


resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1000
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        ignoreExceptions:
          - java.lang.NullPointerException
        retryExceptions: #when retry exceptions is used, ignoreExceptions can be ignored. The same retryExceptions can be configured at gateway server application
          - java.util.concurrent.TimeoutException
