spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
        # search-locations: "classpath:/config"
        # search-locations: "file:///C://Users//..."
        git:
          uri: "https://github.com/santhoshshetty/softbank-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

encrypt:
  key: "45DEEWRWEJCEWR34" #http://localhost:8071/encrypt and put the respective plain text in the body

server:
  port: 8071